# Generated by Django 4.1.2 on 2022-10-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='join_date',
            field=models.DateField(),
        ),
    ]
