# Generated by Django 4.1.2 on 2022-10-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pair',
            old_name='occupant',
            new_name='group',
        ),
    ]
