# Generated by Django 4.1.2 on 2022-10-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_rename_occupant_pair_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pair',
            old_name='is_odd',
            new_name='odd_week',
        ),
    ]
