# Generated by Django 4.1.2 on 2022-11-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_week'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Week',
        ),
    ]
