# Generated by Django 4.1.2 on 2022-10-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('cabinet', models.CharField(max_length=100)),
                ('professor', models.CharField(max_length=100)),
                ('occupant', models.CharField(max_length=100)),
            ],
        ),
    ]
