# Generated by Django 4.1.2 on 2022-10-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cell',
            new_name='Schedule',
        ),
    ]
